import { getBioHashtagSearchPatterns, isBioHashtagSlug } from '@/lib/tags/bioHashtagCategories';

/** Bio-keyword + owner category list. Match bio/name/username/location/categories tag. */
export const OF_KEYWORD_CATEGORIES = [
  { name: "Thin", emoji: '🏷️', slug: "thin", patterns: ["thin"] },
  { name: "Blond", emoji: '🏷️', slug: "blond", patterns: ["\\bblond\\b"] },
  { name: "Egirl", emoji: '🏷️', slug: "egirl", patterns: ["egirl"] },
  { name: "Booty", emoji: '🏷️', slug: "booty", patterns: ["booty"] },
  { name: "Cosplayer", emoji: '🏷️', slug: "cosplayer", patterns: ["cosplayer"] },
  { name: "Twitch", emoji: '🏷️', slug: "twitch", patterns: ["twitch"] },
  { name: "Sub", emoji: '🏷️', slug: "sub", patterns: ["sub"] },
  { name: "Doll", emoji: '🏷️', slug: "doll", patterns: ["doll"] },
  { name: "Dildo", emoji: '🏷️', slug: "dildo", patterns: ["dildo"] },
  { name: "Small", emoji: '🏷️', slug: "small", patterns: ["small"] },
  { name: "Colombia", emoji: '🏷️', slug: "colombia", patterns: ["colombia","colombian","colombiana"] },
  { name: "Curves", emoji: '🏷️', slug: "curves", patterns: ["curves"] },
  { name: "Big Tits", emoji: '🏷️', slug: "big-tits", patterns: ["big tits"] },
  { name: "Squirting", emoji: '🏷️', slug: "squirting", patterns: ["squirting"] },
  { name: "Tiktok", emoji: '🏷️', slug: "tiktok", patterns: ["tiktok"] },
  { name: "Mistress", emoji: '🏷️', slug: "mistress", patterns: ["mistress"] },
  { name: "Tiny", emoji: '🏷️', slug: "tiny", patterns: ["tiny"] },
  { name: "Public", emoji: '🏷️', slug: "public", patterns: ["public"] },
  { name: "Fansly", emoji: '🏷️', slug: "fansly", patterns: ["fansly"] },
  { name: "Türk", emoji: '🏷️', slug: "turkish", patterns: ["türk","turk","turkish"] },
  { name: "Tall", emoji: '🏷️', slug: "tall", patterns: ["tall"] },
  { name: "Short", emoji: '🏷️', slug: "short", patterns: ["short"] },
  { name: "Inked", emoji: '🏷️', slug: "inked", patterns: ["inked"] },
  { name: "London", emoji: '🏷️', slug: "london", patterns: ["london"] },
  { name: "Vegas", emoji: '🏷️', slug: "vegas", patterns: ["vegas"] },
  { name: "Taiwan", emoji: '🏷️', slug: "taiwan", patterns: ["taiwan"] },
  { name: "Dominant", emoji: '🏷️', slug: "dominant", patterns: ["dominant"] },
  { name: "Tatted", emoji: '🏷️', slug: "tatted", patterns: ["tatted"] },
  { name: "Brazil", emoji: '🏷️', slug: "brazil", patterns: ["brazil"] },
  { name: "Domme", emoji: '🏷️', slug: "domme", patterns: ["domme"] },
  { name: "Atlanta", emoji: '🏷️', slug: "atlanta", patterns: ["atlanta"] },
  { name: "Germany", emoji: '🏷️', slug: "germany", patterns: ["germany"] },
  { name: "Huge Tits", emoji: '🏷️', slug: "huge-tits", patterns: ["huge tits"] },
  { name: "Ginger", emoji: '🏷️', slug: "ginger", patterns: ["ginger"] },
  { name: "Thicc", emoji: '🏷️', slug: "thicc", patterns: ["thicc"] },
  { name: "Creampie", emoji: '🏷️', slug: "creampie", patterns: ["creampie"] },
  { name: "Las Vegas", emoji: '🏷️', slug: "las-vegas", patterns: ["las vegas"] },
  { name: "Japan", emoji: '🏷️', slug: "japan", patterns: ["japan"] },
  { name: "Youtube", emoji: '🏷️', slug: "youtube", patterns: ["youtube"] },
  { name: "Foot Fetish", emoji: '🏷️', slug: "foot-fetish", patterns: ["foot fetish"] },
  { name: "Bratty", emoji: '🏷️', slug: "bratty", patterns: ["bratty"] },
  { name: "Morocco", emoji: '🏷️', slug: "morocco", patterns: ["morocco"] },
  { name: "Facial", emoji: '🏷️', slug: "facial", patterns: ["facial"] },
  { name: "Greece", emoji: '🏷️', slug: "greece", patterns: ["greece"] },
  { name: "Australia", emoji: '🏷️', slug: "australia", patterns: ["australia"] },
  { name: "Miami", emoji: '🏷️', slug: "miami", patterns: ["miami"] },
  { name: "Slim", emoji: '🏷️', slug: "slim", patterns: ["slim"] },
  { name: "Slave", emoji: '🏷️', slug: "slave", patterns: ["slave"] },
  { name: "Emo", emoji: '🏷️', slug: "emo", patterns: ["emo"] },
  { name: "Argentina", emoji: '🏷️', slug: "argentina", patterns: ["argentina"] },
  { name: "Leather", emoji: '🏷️', slug: "leather", patterns: ["leather"] },
  { name: "Gothic", emoji: '🏷️', slug: "gothic", patterns: ["gothic"] },
  { name: "Skinny", emoji: '🏷️', slug: "skinny", patterns: ["skinny"] },
  { name: "Model", emoji: '🏷️', slug: "model", patterns: ["model","modelling","modeling"] },
  { name: "Nude", emoji: '🏷️', slug: "nude", patterns: ["nude","naked","full nude"] },
  { name: "Fetish", emoji: '🏷️', slug: "fetish", patterns: ["fetish","kinky"] },
  { name: "E-girl", emoji: '🏷️', slug: "e-girl", patterns: ["e-girl","egirl","e girl"] },
  { name: "Solo", emoji: '🏷️', slug: "solo", patterns: ["solo content"," solo ","solo play"] },
  { name: "Custom", emoji: '🏷️', slug: "custom", patterns: ["custom content","custom video","custom request"] },
  { name: "OnlyFans Free", emoji: '🏷️', slug: "onlyfans-free", patterns: ["free onlyfans","free page","free subscription"] },
  { name: "Sexting", emoji: '🏷️', slug: "sexting", patterns: ["sexting","sex chat","dirty talk"] },
  { name: "Busty", emoji: '🏷️', slug: "busty", patterns: ["busty","big boobs","big tits","huge tits","big naturals"] },
  { name: "Gamer", emoji: '🏷️', slug: "gamer", patterns: ["gamer","gaming","playstation","xbox"] },
  { name: "Toys", emoji: '🏷️', slug: "toys", patterns: ["toys","dildo","vibrator","sex toy"] },
  { name: "Anime", emoji: '🏷️', slug: "anime", patterns: ["anime","waifu","hentai"] },
  { name: "Dominatrix", emoji: '🏷️', slug: "dominatrix", patterns: ["dominatrix","femdom","mistress","domme"] },
  { name: "Girlfriend", emoji: '🏷️', slug: "girlfriend", patterns: ["girlfriend","gfe","girlfriend experience"] },
  { name: "Mommy", emoji: '🏷️', slug: "mommy", patterns: ["mommy","mummy"," stepmom ","step mom"] },
  { name: "Instagram", emoji: '🏷️', slug: "instagram", patterns: ["instagram","insta model","ig model"] },
  { name: "Oral", emoji: '🏷️', slug: "oral", patterns: ["blowjob","deepthroat"," oral "] },
  { name: "PAWG", emoji: '🏷️', slug: "pawg", patterns: ["pawg","phat ass white"] },
  { name: "Bikini", emoji: '🏷️', slug: "bikini", patterns: ["bikini","swimsuit","beach body"] },
  { name: "College", emoji: '🏷️', slug: "college", patterns: ["college","university","campus","student"] },
  { name: "Dancer", emoji: '🏷️', slug: "dancer", patterns: ["dancer","dancing","ballet","pole dance","stripper"] },
  { name: "Neighbor", emoji: '🏷️', slug: "neighbor", patterns: ["neighbor","neighbour","girl next door"] },
  { name: "Femdom", emoji: '🏷️', slug: "femdom", patterns: ["femdom","female dom"] },
  { name: "Big Booty", emoji: '🏷️', slug: "big-booty", patterns: ["big booty","phat booty"] },
  { name: "Natural", emoji: '🏷️', slug: "natural", patterns: ["natural boobs","natural tits","all natural"] },
  { name: "Hotwife", emoji: '🏷️', slug: "hotwife", patterns: ["hotwife","cuckold","cuck"] },
  { name: "Girl Next Door", emoji: '🏷️', slug: "girl-next-door", patterns: ["girl next door"] },
  { name: "German", emoji: '🏷️', slug: "german", patterns: ["german","germany","deutsch"] },
  { name: "Yoga", emoji: '🏷️', slug: "yoga", patterns: ["yoga","flexible","stretch"] },
  { name: "Bondage", emoji: '🏷️', slug: "bondage", patterns: ["bondage","tied up","rope"] },
  { name: "Bisexual", emoji: '🏷️', slug: "bisexual", patterns: ["bisexual"," bi ","bi curious"] },
  { name: "Australian", emoji: '🏷️', slug: "australian", patterns: ["australian","australia","aussie"] },
  { name: "Video Call", emoji: '🏷️', slug: "video-call", patterns: ["video call","facetime","cam call"] },
  { name: "POV", emoji: '🏷️', slug: "pov", patterns: ["pov ","point of view"] },
  { name: "Taiwanese", emoji: '🏷️', slug: "taiwanese", patterns: ["taiwan","taiwanese"] },
  { name: "Greek", emoji: '🏷️', slug: "greek", patterns: ["greek","greece","athens greece"] },
  { name: "Canadian", emoji: '🏷️', slug: "canadian", patterns: ["canadian","canada"] },
  { name: "Heels", emoji: '🏷️', slug: "heels", patterns: ["high heels","heels"] },
  { name: "Nevada", emoji: '🏷️', slug: "nevada", patterns: ["\\bnevada\\b","\\blas vegas\\b","\\bvegas\\b",", nv\\b"] },
  { name: "Threesome", emoji: '🏷️', slug: "threesome", patterns: ["threesome","3some","three way"] },
  { name: "Florida", emoji: '🏷️', slug: "florida", patterns: ["\\bflorida\\b","\\bmiami\\b","\\borlando\\b","\\btampa\\b",", fl\\b","\\bsouth beach\\b"] },
  { name: "GFE", emoji: '🏷️', slug: "gfe", patterns: ["gfe","girlfriend experience"] },
  { name: "California", emoji: '🏷️', slug: "california", patterns: ["\\bcalifornia\\b","\\blos angeles\\b","\\bsan francisco\\b","\\bsan diego\\b",", ca\\b","\\bhollywood\\b","\\bsocal\\b"] },
  { name: "Goth Girl", emoji: '🏷️', slug: "goth-girl", patterns: ["goth girl"] },
  { name: "Georgia", emoji: '🏷️', slug: "georgia", patterns: ["\\bgeorgia,\\b","\\bgeorgia usa\\b","\\batlanta\\b",", ga\\b"] },
  { name: "Moroccan", emoji: '🏷️', slug: "moroccan", patterns: ["moroccan","morocco","maroc"] },
  { name: "Dick Rating", emoji: '🏷️', slug: "dick-rating", patterns: ["dick rating","cock rating"] },
  { name: "French", emoji: '🏷️', slug: "french", patterns: ["french","france","française"] },
  { name: "Shaved", emoji: '🏷️', slug: "shaved", patterns: ["shaved","smooth","bare"] },
  { name: "Spanish", emoji: '🏷️', slug: "spanish", patterns: ["spanish","spain","español"] },
  { name: "Topless", emoji: '🏷️', slug: "topless", patterns: ["topless","tits out"] },
  { name: "Italian", emoji: '🏷️', slug: "italian", patterns: ["italian","italy","italiana"] },
  { name: "Stockings", emoji: '🏷️', slug: "stockings", patterns: ["stockings","nylon","pantyhose"] },
  { name: "Latex", emoji: '🏷️', slug: "latex", patterns: ["latex","rubber fetish"] },
  { name: "Japanese", emoji: '🏷️', slug: "japanese", patterns: ["japanese","japan","tokyo girl"] },
  { name: "Hairy", emoji: '🏷️', slug: "hairy", patterns: ["hairy","bush","natural hair"] },
  { name: "Argentinian", emoji: '🏷️', slug: "argentinian", patterns: ["argentinian","argentina"] },
  { name: "Catgirl", emoji: '🏷️', slug: "catgirl", patterns: ["catgirl","cat girl","neko"] },
  { name: "Texas", emoji: '🏷️', slug: "texas", patterns: ["\\btexas\\b","\\bhouston\\b","\\bdallas\\b","\\baustin\\b",", tx\\b"] },
  { name: "Thai", emoji: '🏷️', slug: "thai", patterns: ["thai","thailand","bangkok"] },
  { name: "Bunny Girl", emoji: '🏷️', slug: "bunny-girl", patterns: ["bunny girl","playboy bunny"," bunny "] },
  { name: "Mexican", emoji: '🏷️', slug: "mexican", patterns: ["mexican","mexico","mexicana"] },
  { name: "Chinese", emoji: '🏷️', slug: "chinese", patterns: ["chinese","china","mandarin"] },
  { name: "Exotic", emoji: '🏷️', slug: "exotic", patterns: ["exotic","exotic dancer"] },
  { name: "American", emoji: '🏷️', slug: "american", patterns: ["american","usa girl","united states"] },
  { name: "Maid", emoji: '🏷️', slug: "maid", patterns: ["maid","french maid"] },
  { name: "Live Show", emoji: '🏷️', slug: "live-show", patterns: ["live show","live stream show"] },
  { name: "New York", emoji: '🏷️', slug: "new-york", patterns: ["\\bnew york\\b","\\bnyc\\b","\\bmanhattan\\b","\\bbrooklyn\\b",", ny\\b"] },
  { name: "Michigan", emoji: '🏷️', slug: "michigan", patterns: ["\\bmichigan\\b","\\bdetroit\\b",", mi\\b"] },
  { name: "Ukrainian", emoji: '🏷️', slug: "ukrainian", patterns: ["ukrainian","ukraine"] },
  { name: "College Girl", emoji: '🏷️', slug: "college-girl", patterns: ["college girl"] },
  { name: "Polish", emoji: '🏷️', slug: "polish", patterns: ["polish","poland","polska"] },
  { name: "Russian", emoji: '🏷️', slug: "russian", patterns: ["russian","russia"] },
  { name: "Scottish", emoji: '🏷️', slug: "scottish", patterns: ["scottish","scotland","scots"] },
  { name: "Massachusetts", emoji: '🏷️', slug: "massachusetts", patterns: ["\\bmassachusetts\\b","\\bboston\\b",", ma\\b"] },
  { name: "Step Fantasy", emoji: '🏷️', slug: "step-fantasy", patterns: ["step fantasy","stepmom","step sister","stepdaughter"] },
  { name: "New Zealand", emoji: '🏷️', slug: "new-zealand", patterns: ["new zealand","kiwi","nz girl"] },
  { name: "Filipina", emoji: '🏷️', slug: "filipina", patterns: ["filipina","filipino","philippines","pinay"] },
  { name: "Colorado", emoji: '🏷️', slug: "colorado", patterns: ["\\bcolorado\\b","\\bdenver\\b",", co\\b"] },
  { name: "Peruvian", emoji: '🏷️', slug: "peruvian", patterns: ["peruvian","peru"] },
  { name: "Persian", emoji: '🏷️', slug: "persian", patterns: ["persian","iranian","iran"] },
  { name: "Irish", emoji: '🏷️', slug: "irish", patterns: ["irish","ireland","dublin"] },
  { name: "Swedish", emoji: '🏷️', slug: "swedish", patterns: ["swedish","sweden"] },
  { name: "Dutch", emoji: '🏷️', slug: "dutch", patterns: ["dutch","netherlands","holland"] },
  { name: "South Korean", emoji: '🏷️', slug: "south-korean", patterns: ["korean","korea","seoul korea"] },
  { name: "Illinois", emoji: '🏷️', slug: "illinois", patterns: ["\\billinois\\b","\\bchicago\\b",", il\\b"] },
  { name: "Korean", emoji: '🏷️', slug: "korean", patterns: ["korean","korea","seoul korea"] },
  { name: "Norwegian", emoji: '🏷️', slug: "norwegian", patterns: ["norwegian","norway"] },
  { name: "Romanian", emoji: '🏷️', slug: "romanian", patterns: ["romanian","romania"] },
  { name: "Chilean", emoji: '🏷️', slug: "chilean", patterns: ["chilean","chile"] },
  { name: "Arizona", emoji: '🏷️', slug: "arizona", patterns: ["\\barizona\\b","\\bphoenix\\b",", az\\b"] },
  { name: "Ecuadorian", emoji: '🏷️', slug: "ecuadorian", patterns: ["ecuadorian","ecuador"] },
  { name: "Finnish", emoji: '🏷️', slug: "finnish", patterns: ["finnish","finland"] },
  { name: "Czech", emoji: '🏷️', slug: "czech", patterns: ["czech","czechia"] },
  { name: "Couple Lesbian", emoji: '🏷️', slug: "couple-lesbian", patterns: ["lesbian couple","girl on girl couple"] },
  { name: "Puerto Rican", emoji: '🏷️', slug: "puerto-rican", patterns: ["puerto rican","puerto rico"] },
  { name: "North Carolina", emoji: '🏷️', slug: "north-carolina", patterns: ["\\bnorth carolina\\b","\\bcharlotte\\b","\\braleigh\\b",", nc\\b"] },
  { name: "Public Sex", emoji: '🏷️', slug: "public-sex", patterns: ["public sex","public play","outdoor sex"] },
  { name: "Caucasian", emoji: '🏷️', slug: "caucasian", patterns: ["caucasian","white girl"] },
  { name: "Singaporean", emoji: '🏷️', slug: "singaporean", patterns: ["singaporean","singapore"] },
  { name: "Asexual", emoji: '🏷️', slug: "asexual", patterns: ["asexual"," ace "] },
  { name: "Bulgarian", emoji: '🏷️', slug: "bulgarian", patterns: ["bulgarian","bulgaria"] },
  { name: "Couple Straight", emoji: '🏷️', slug: "couple-straight", patterns: ["straight couple","boy girl couple"] },
  { name: "Croatian", emoji: '🏷️', slug: "croatian", patterns: ["croatian","croatia"] },
  { name: "Malaysian", emoji: '🏷️', slug: "malaysian", patterns: ["malaysian","malaysia"] },
  { name: "Shower Sex", emoji: '🏷️', slug: "shower-sex", patterns: ["shower sex","shower play"] },
  { name: "Slovak", emoji: '🏷️', slug: "slovak", patterns: ["slovak","slovakia"] },
  // Flag-audit 15+ — country noun slug (demonym slug already live)
  { name: "Canada", emoji: '🏷️', slug: "canada", patterns: ["canadian","canada","toronto","vancouver","montreal"] },
  { name: "USA", emoji: '🏷️', slug: "usa", patterns: ["american","usa girl","united states","\\busa\\b"] },
  { name: "UK", emoji: '🏷️', slug: "uk", patterns: ["british","english girl","england","uk girl","brit","united kingdom"] },
  { name: "Mexico", emoji: '🏷️', slug: "mexico", patterns: ["mexican","mexico","mexicana"] },
  { name: "Italy", emoji: '🏷️', slug: "italy", patterns: ["italian","italy","italiana"] },
  { name: "Spain", emoji: '🏷️', slug: "spain", patterns: ["spanish","spain","español"] },
  { name: "France", emoji: '🏷️', slug: "france", patterns: ["french","france","française"] },
  { name: "Thailand", emoji: '🏷️', slug: "thailand", patterns: ["thai","thailand","bangkok"] },
  { name: "Turkey", emoji: '🏷️', slug: "turkey", patterns: ["turkish","turkey","türk","tür"] },
  { name: "Ukraine", emoji: '🏷️', slug: "ukraine", patterns: ["ukrainian","ukraine"] },
  { name: "Puerto Rico", emoji: '🏷️', slug: "puerto-rico", patterns: ["puerto rican","puerto rico"] },
  { name: "Georgian", emoji: '🏷️', slug: "georgian", patterns: ["georgian","tbilisi"] },
  { name: "Gamer Girl", emoji: '🏷️', slug: "gamer-girl", patterns: ["gamer girl","gamergirl"] },
  { name: "Gym", emoji: '🏷️', slug: "gym", patterns: ["gym"] },
  { name: "Titties", emoji: '🏷️', slug: "titties", patterns: ["titties"] },
  { name: "Cam Girl", emoji: '🏷️', slug: "cam-girl", patterns: ["camgirl","cam girl"] },
] as const;

/** Bio patterns for base OF categories (same slug as constants.ts — no duplicate row). */
export const OF_BASE_CATEGORY_PATTERNS: Record<string, readonly string[]> = {
  'big-ass': ['big ass', 'bigass'],
  'big-boobs': ['big boobs', 'bigboobs', 'bigtits', 'bittits'],
  goth: ['goth', 'gothgirl'],
  cosplay: ['cosplay', 'cosplaygirl'],
  colombian: ['colombian', 'colombiana', 'colombia'],
};

export type OfKeywordCategory = (typeof OF_KEYWORD_CATEGORIES)[number];

const PATTERN_MAP = new Map(OF_KEYWORD_CATEGORIES.map((c) => [c.slug, [...c.patterns]]));
const BASE_PATTERN_MAP = new Map(Object.entries(OF_BASE_CATEGORY_PATTERNS));

export function getKeywordCategoryPatterns(slug: string): string[] | undefined {
  const kw = PATTERN_MAP.get(slug);
  const base = BASE_PATTERN_MAP.get(slug);
  const bio = getBioHashtagSearchPatterns(slug);
  const merged = [...new Set([...(kw ?? []), ...(base ?? []), ...bio])];
  return merged.length ? merged : undefined;
}

export function isKeywordOfCategory(slug: string): boolean {
  return PATTERN_MAP.has(slug) || BASE_PATTERN_MAP.has(slug) || isBioHashtagSlug(slug);
}
