export const categories = [
    'All', 'Amateur', 'Anal', 'Asian', 'BDSM', 'Big Ass', 'Big Tits', 'Blowjob',
    'Creampie', 'Cuckold', 'Ebony', 'Fetish', 'Gangbang', 'Gay', 'Group',
    'Hardcore', 'Interracial', 'Latina', 'Lesbian', 'MILF', 'Public', 'Roleplay',
    'Romantic', 'Teen (18+)', 'Threesome', 'Trans', 'Voyeur', 'LGBTQ+', 'Fantasy',
    'Adult Chat', 'Cosplay', 'Cosplay - Anime', 'Cosplay - Video Games',
    'Cosplay - Movies/TV', 'Cosplay - Comics', 'Feet', 'SFW', 'POV', 'Mature',
    'Vintage', 'BDSM Lite', 'Medical', 'Erotic Horror', 'Office', 'Outdoor',
    'Celebrity Lookalike', 'Roleplay - Teacher/Student', 'Roleplay - Nurse/Doctor',
    'Costume', 'Taboo', 'Tickling', 'Uniforms',
    'Cosplay - Fantasy', 'Furry', 'Pet Play', 'Double Penetration', 'Mind Control',
    'Submission', 'Domination', 'Glasses', 'Hair Play', 'Oral', 'Lesbian Tribbing',
    'Masturbation', 'Latex', 'Squirting', 'Spanking', 'Tease & Denial',
    'Cosplay - Sci-Fi', 'Steampunk',
    'Hentai', 'Anime', 'Hentai - Loli', 'Hentai - Shota', 'Hentai - Yaoi', 'Hentai - Yuri',
    'Hentai - Tentacle', 'Hentai - Monster', 'Hentai - Futanari', 'Hentai - Incest',
    'Hentai - Noncon', 'Hentai - Beast', 'Hentai - Ecchi', 'Anime Porn', 'Hentai - BDSM',
    'Hentai - Schoolgirl', 'Hentai - Magical Girl', 'Hentai - Mecha', 'Hentai - Trap',
    'Hentai - Ahegao', 'Hentai - Bondage', 'Hentai - Gangbang', 'Hentai - Milf',
    'Hentai - Lolicon', 'Hentai - Shotacon', 'Anime Fetish', 'Hentai - Public',
    'Hentai - Mind Break', 'Hentai - Domination', 'Hentai - Submission',
    'Anime Cosplay Sex', 'Hentai - Pet Play', 'Hentai - Furry', 'Hentai - Monster Girl',
];

export const countries = [
    'All', 'USA', 'UK', 'Germany', 'France', 'Brazil', 'Russia', 'Japan',
    'South Korea', 'Philippines', 'Thailand', 'Spain', 'Mexico', 'Canada',
    'Australia', 'Italy', 'Netherlands', 'Czech Republic', 'China', 'Argentina',
    'South Africa', 'Nigeria', 'Turkey', 'Indonesia', 'Pakistan', 'Bangladesh',
    'Vietnam', 'Malaysia', 'Singapore', 'New Zealand', 'Sweden', 'Norway', 'Denmark',
    'Finland', 'Poland', 'Ukraine', 'Egypt', 'Saudi Arabia', 'United Arab Emirates',
    'Israel', 'Iran', 'Iraq', 'Algeria', 'Morocco', 'Ethiopia', 'Kenya', 'Ghana',
    'Colombia', 'Chile', 'Peru', 'Venezuela', 'Ecuador', 'Bolivia', 'Paraguay',
    'Uruguay', 'Costa Rica', 'Panama', 'Dominican Republic', 'Cuba', 'Portugal',
    'Belgium', 'Switzerland', 'Austria', 'Greece', 'Ireland', 'Hungary', 'Romania',
    'Bulgaria', 'Croatia', 'Serbia', 'Slovakia', 'Slovenia', 'Lithuania', 'Latvia',
    'Estonia', 'Iceland', 'Luxembourg', 'Malta', 'Cyprus', 'Qatar', 'Kuwait',
    'Oman', 'Bahrain', 'Jordan', 'Lebanon', 'Syria', 'Yemen', 'Afghanistan',
    'Sri Lanka', 'Nepal', 'Bhutan', 'Maldives', 'Myanmar', 'Cambodia', 'Laos',
    'Mongolia', 'Taiwan', 'Hong Kong', 'Macau', 'Kazakhstan',
];
