import type { AINsfwFullReview } from './reviewTypes';

/** Full editorial reviews keyed by tool.slug. Generated by scripts/generate-ainsfw-full-review.mjs */
export const AINSFW_FULL_REVIEWS: Record<string, AINsfwFullReview> = {
  "girlfriendgpt-ai-girlfriend": {
    shortDescription: "GirlfriendGPT is a platform where artificial intelligence turns companionship into something users can shape with their own hands. The service belongs to the NextDay AI group and has grown into one of the busier corners of the AI girlfriend scene. Its main attraction lets users build a virtual girlfriend from zero, from her looks all the way to her temper. The library counts more than 25,000 characters made by the community, so people who don't feel like creating can simply pick one and start chatting.",
    featureHighlights: [
      {
        title: "Build Your Own Companion",
        body: "The character builder is the heart of GirlfriendGPT, and it is a generous one. Users write out her personality, her past, and how the relationship should behave, and the AI keeps these instructions close during every conversation. The details stick, so she doesn't forget what was said two weeks ago. Members can save several characters and jump between them as the mood strikes.",
      },
      {
        title: "Pictures Inside the Chat",
        body: "GirlfriendGPT lets users request images right in the middle of a conversation. The AI girlfriend can show what she is wearing, or not wearing, based on where the story went. The quality is good on simple requests, but busy scenes sometimes come out strange and need another try. This feature belongs to the paid plans.",
      },
      {
        title: "She Can Talk Back",
        body: "Voice messages are the other paid treat. The girlfriend sends spoken replies, which makes the whole affair less of a texting exercise. The voices are pleasant, although long sentences occasionally trip it up.",
      },
    ],
    sections: [
      {
        heading: "GirlfriendGPT Review",
        body: "GirlfriendGPT is a clean and welcoming platform, even for people who never touched an AI companion before. Visitors receive 50 free messages per day, which is more than enough to see if the chemistry is there. The serious features, images, voice, and full NSFW conversations, are kept behind the subscription, as expected. Everything happens in the browser, since a mobile app is nowhere to be found for now. Chats stay private and accounts can remain anonymous.",
      },
      {
        heading: "How Does It Work",
        body: "GirlfriendGPT does the heavy lifting in the background so users never have to think about it. A new visitor picks a girlfriend from the library or builds one, and the conversation starts immediately. The AI reads the character sheet and the chat history before every reply, which keeps the story from falling apart.\n\nThe image generator and the voice tool plug directly into the chat window. Users ask, and the results appear within the conversation itself, not in some separate menu. Free members will hit the daily message ceiling sooner or later, and the memory on the free plan is on the short side, so long romances are better lived on a subscription.\n\nDescriptive users get the best out of GirlfriendGPT. The more precise the instructions, the more the girlfriend behaves like the one imagined. Vague prompts produce vague girlfriends, and that is nobody's fault but the writer's.",
      },
      {
        heading: "How to Subscribe",
        body: "The free plan is the bait, and it works. Fifty messages a day, most of the character library, and a real taste of the conversations. However, the pictures, the voice, and the uncensored material wait on the other side of the paywall. The Deluxe plan costs $12 per month and brings 5,000 messages, 400 images monthly, voice replies, and the full NSFW experience. Heavy users can look at the Elite plan, billed yearly at $27.50 per month, with unlimited messages and priority processing. There are no coins or tokens to juggle, the subscription covers everything, which keeps things simple.",
      },
      {
        heading: "A Girlfriend Worth Keeping",
        body: "GirlfriendGPT is a platform where users design a companion, talk with her, see her, and hear her. The free tier is honest and the paid plans are reasonably priced for what they unlock. The missing mobile app is the main complaint, and the message caps push active users toward the bigger plans, as these things go. For anyone curious about an AI girlfriend that remembers, speaks, and poses, GirlfriendGPT is among the first doors worth knocking on.",
      },
    ],
  },
  "joi-ai-nude-generator": {
    shortDescription: "JOI AI is a platform where an AI companion, an image generator, and short video clips live under one roof. The service started life as EVA AI, years before the current wave of companion apps, and rebranded in 2025 around the idea of AI-lationships. Members build a character from zero, chat with her, ask the nude ai generator for pictures, and turn her into short video moments called Dream Clips. The free plan opens the door, and the subscription unlocks the full experience.",
    featureHighlights: [
      {
        title: "Build Her From Zero",
        body: "The character creator is the deepest part of JOI AI, and the part members spend the most time in. Users shape appearance, conversational tone, emotional behavior, and how the relationship acts, closer to writing a roleplay persona than filling a settings form. The details stay put across long conversations, so she remembers what was said days ago. A shared community library exists for people who would rather pick than build.",
      },
      {
        title: "Pictures From the Chat",
        body: "JOI AI works as an ai photo generator for nudes in the plain sense. Users describe the scene, choose realistic or anime, set the orientation, and add negative prompts for extra control. Renders arrive in under a minute and stay tied to the character, so the face carries between images. Realistic nude photos come out closer to photography than most first-timers expect, with skin texture that holds up and lighting that behaves.",
      },
      {
        title: "Dream Clips",
        body: "Dream Clips are short AI-generated video moments built from a character and a prompt, and nobody else in the category offers anything like them. Even a simple prompt turns a still character into a moving scene, which makes JOI AI feel like an entertainment platform instead of a chat window. If one feature justifies the subscription by itself, this is the one.",
      },
    ],
    sections: [
      {
        heading: "JOI AI Review",
        body: "JOI AI is a polished platform, and the polish has a simple explanation: the product has been iterating for years under the EVA AI name while most competitors were built in a weekend. Conversations keep their tone over hours instead of collapsing into generic replies after ten minutes. Characters stay consistent, which sounds basic and is anything but in this category. The free plan is a genuine way to test the chemistry before spending anything. Everything happens in the browser and on mobile, and accounts can stay anonymous.",
      },
      {
        heading: "How Does It Work",
        body: "A new visitor picks a companion from the community library or builds one in the creator. The AI reads the character sheet and the conversation history before every reply, which keeps long stories from falling apart. The image generator and Dream Clips plug into the same ecosystem, so the character made in chat is the one that appears in the pictures and the videos.\n\nThe nude ai side works from text. Users describe what they want and the engine returns a batch within the minute. Anime and photoreal styles are both tuned hard, so members get strong results whichever lane they prefer.\n\nDescriptive users get the best out of the platform. The more personality cues and context the member provides, the stronger the replies and the renders become. Vague prompts produce vague companions, and that is nobody's fault but the writer's.",
      },
      {
        heading: "How to Subscribe",
        body: "The free plan covers basic chatting and enough generation to see whether the workflow fits. Premium runs around $10 to $14 per month and brings full chat access, NSFW mode, and Dream Clips. A higher tier near $20 per month adds extended memory and faster generation. Annual deals get discounted heavily during promotions and are clearly where the value sits.\n\nPower users can top up with Neurons, the internal currency, for advanced generations and exclusive unlocks whenever the mood strikes. The subscription covers the core experience, and Neurons are there for members who want more.",
      },
      {
        heading: "JOI AI Compared",
        body: "GirlfriendGPT offers a bigger community character library, and aiAllure leans into scenario storytelling. JOI AI takes the all-rounder crown: no other platform in the category combines character depth, a capable nude ai generator, and video in one place.",
      },
      {
        heading: "A Companion With a Film Career",
        body: "JOI AI is a platform where users design a companion, talk with her, see her, and put her in motion. The conversations are better than the category average, the character creator is the best around, and Dream Clips have no real competition. For anyone curious about an AI companion that chats, renders realistic nude photos, and stars in her own short clips, JOI AI is the first door worth knocking on. The free plan makes trying it a no-risk affair, and the first render argues for itself.",
      },
    ],
    alternatives: [
      { name: "GirlfriendGPT", slug: "girlfriendgpt-ai-girlfriend" },
      { name: "aiAllure", slug: "aiallure-ai-chat" },
      { name: "Lovescape", slug: "lovescape-ai-girlfriend" },
    ],
  },
  "free-nudifier-undress-ai": {
    shortDescription: "Free Nudifier is a browser-based undress tool that lives at freenudifier.com and asks nothing of the visitor before the first result. No account, no email, no card. A user drops a clothed photo, waits somewhere between ten and thirty seconds, and downloads the nude version, and the basic undress output arrives without a watermark, which is not the norm in this niche. The tool takes JPG, PNG, and WebP files up to 10MB, runs on cloud GPUs, and processes everything server-side so the images are not kept afterward. For a category where most rivals hide even a single test behind a signup wall, the open door is the main draw.",
    featureHighlights: [
      {
        title: "Instant Free Undress",
        body: "The free tier is a real working tool, not a teaser. Basic undress runs without limits on account creation, and the results keep the original lighting and pose reasonably intact. Busy backgrounds or awkward angles sometimes need a second try, as expected.",
      },
      {
        title: "A Large Effect Library on the Paid Side",
        body: "Beyond the free undress, the demo shows a much bigger catalog that unlocks with a paid upgrade to Mixvid. That side carries 120+ image effects, from pose presets to body edits, and over 300 image-to-video animations built from a single photo. Photoreal mode and ultra detail enhancement also sit behind the paywall.",
      },
      {
        title: "One-Time Credits, No Subscription",
        body: "Free Nudifier avoids the monthly-plan trap. Paid access works on credit packs that never expire: 200 credits for $9.99, 800 for $29.99, 2,000 for $59.99, and 10,000 for $249.99. The bigger the pack, the cheaper each credit becomes, so heavy users are rewarded and casual ones are not locked into a recurring charge.",
      },
    ],
    sections: [
      {
        heading: "Free Nudifier Review",
        body: "The tool does one thing very well and then quietly points to a full studio for anyone who wants more. The free entry is genuinely free and genuinely useful, and the upgrade path is there without nagging on every screen. The branding is a little confusing, since the site calls the premium platform Mixvid while the checkout runs under a related name, and that is worth a mention but not a dealbreaker.",
      },
      {
        heading: "The Verdict",
        body: "Free Nudifier is one of the first doors worth knocking on for anyone curious about AI undress. Instant, free, no account, with real depth waiting on the other side of the credits.",
      },
    ],
    alternatives: [
      { name: "Nudify.VIP", slug: "nudify-vip-undress-ai" },
      { name: "Unclothy", slug: "unclothy-undress-ai" },
      { name: "Fastundress", slug: "fastundress-undress-ai" },
    ],
  },
};

export function getFullReview(slug: string): AINsfwFullReview | undefined {
  return AINSFW_FULL_REVIEWS[slug];
}

/** Paid submission slugs that have an editorial full review (verified badge). */
export function getVerifiedPaidSlugs(paidSlugs: Iterable<string>): string[] {
  const out: string[] = [];
  for (const slug of paidSlugs) {
    if (AINSFW_FULL_REVIEWS[slug]) out.push(slug);
  }
  return out;
}
